import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#ddb892] to-[#fff] text-white">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <Image
            src="/logo.svg"
            width={500}
            height={500}
            alt="coffee shop logo"
          />
        </div>
      </main>
    </>
  );
};

export default Home;
