import Head from "next/head";

type ContainerProps = {
  children: React.ReactNode;
};

export default function Container({ children }: ContainerProps) {
  return (
    <>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      {children}
    </>
  );
}
